name: Release

on:
  workflow_dispatch:
    inputs:
      placeholder:
        description: "Placeholder"

jobs:
  placeholder:

    runs-on: ubuntu-latest

    steps:
    - name: placeholder
      run: echo Placeholder running