name: Release Rogue Forever

# GitHub actions permissions can be changed from:
# Settings -> Actions -> General

on:
  # workflow_dispatch: needs to be in main branch before 'Run workflow'
  # button appears on GitHub actions page.
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Git tag to checkout for releasing"

jobs:
  new_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.release_tag }}

    - name: Print summary of latest commit
      run: git show --stat HEAD

    - name: Create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: ${{ github.event.inputs.release_tag }}
      run:
        ./scripts/create_release.sh
